# Generated by Django 5.2.7 on 2026-04-16 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_grades_student_alter_users_email_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField()),
                ('paid', models.BooleanField(default=True)),
                ('month', models.CharField(choices=[('jan', 'Январь'), ('feb', 'Февраль'), ('mar', 'Март'), ('apr', 'Апрель'), ('may', 'Май'), ('jun', 'Июнь'), ('jul', 'Июль'), ('aug', 'Август'), ('sep', 'Сентябрь'), ('oct', 'Октябрь'), ('nov', 'Ноябрь'), ('dec', 'Декабрь')], max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
